### ISSUE TITLE
Regular Expression Support

### ISSUE THREAD

**Issue by balanscott** [Project-Herophilus/DataSynthesis#89]
We need to have more documented regular expressions for the platform to leverage to generate data against. Can we get a list of some common regular expressions we can use within the platform? Some examples of things would be:

- International Phone Numbers (multiple countries)
- Country National IDs
- Email Addresses

**Comment by GonzoJrETU** [comment]
I'm including several links that will help with creating more RegEx patterns.  

Microsoft Purview has a list of over 280 common terms and describes the pattern in English.
[https://learn.microsoft.com/en-us/azure/purview/supported-classifications](https://learn.microsoft.com/en-us/azure/purview/supported-classifications)

We may also consider leveraging the Python library named Faker as we build out the data generator scripts in Notebooks.
[https://faker.readthedocs.io/en/master/](https://faker.readthedocs.io/en/master/)

Video: [https://youtu.be/VJAEMZt_Uh0?t=28](https://youtu.be/VJAEMZt_Uh0?t=28)

**Comment by balanscott** [comment]
Please go ahead and cut and paste your comment into the file
